dir = "C:/Users/error/PycharmProjects/ml/"
dir = "A:/PhD/ml/"

data_dir = "A:/PhD/ml/data/"#"C:/Users/error/PycharmProjects/ml/data/"

histories_dir = dir + "histories/"

model_dir = dir + "models/"

exp_property_visualisation = data_dir+"property_visualisation/"

backup_dir = data_dir + "backup/"
shapes_complex_dir = data_dir + "complex/"
shapes_simple_dir = data_dir + "simple/"
shapes_left_dir = data_dir + "left/"
shapes_right_dir = data_dir + "right/"
shapes_interpolated = data_dir + "inter/"
shapes_interpolated_up = shapes_interpolated + "u/"
shapes_interpolated_down = shapes_interpolated + "d/"
shapes_interpolated_center = shapes_interpolated + "c/"
circle_interpolated_up = shapes_interpolated + "circle/u/"
circle_interpolated_down = shapes_interpolated + "circle/d/"
circle_interpolated_center = shapes_interpolated + "circle/c/"
triangle_interpolated_up = shapes_interpolated + "triangle/u/"
triangle_interpolated_down = shapes_interpolated + "triangle/d/"
triangle_interpolated_center = shapes_interpolated + "triangle/c/"
triangle_interpolated_test = shapes_interpolated + "triangle/test/"
square_interpolated_up = shapes_interpolated + "square/u/"
square_interpolated_down = shapes_interpolated + "square/d/"
square_interpolated_center = shapes_interpolated + "square/c/"
shapes_interpolated_custom= shapes_interpolated + "custom/"
shapes_interpolated_custom_mixed= shapes_interpolated + "custom_mixed/"
square_and_circle_interpolated_custom_mixed= shapes_interpolated + "custom_square_and_circle/"
square_and_triangle_interpolated = shapes_interpolated + "square_triangle/"
shapes_interpolated_custom_mixed_old= backup_dir +"custom_mixed_OLD/"
negative_dir = data_dir + "negative/"
